version: "3.9"
services:
  web:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - "3308:3306"
    volumes:
        - ./data/application/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./data/application/init_timescale.sql:/docker-entrypoint-initdb.d/init.sql
