version: "3.9"
services:
  web:
    build: .
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 80 --reload"
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - timescaledb
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./manual_conversion/init_timescale.sql:/docker-entrypoint-initdb.d/init.sql
