version: "3.9"
services:
  web:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - "3308:3306"
    env_file:
      - .env
