"""Intitial conversion - modify tables

Revision ID: 84965ab12140
Revises: 
Create Date: 2022-11-25 11:34:12.836921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84965ab12140'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'weather_real_time', 'weather_stations', ['station_id'], ['station_id'])
    op.add_column('weather_stations', sa.Column('api_key', sa.Text(), nullable=False))
    op.create_unique_constraint('location', 'weather_stations', ['longitude', 'latitude'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('location', 'weather_stations', type_='unique')
    op.drop_column('weather_stations', 'api_key')
    op.drop_constraint(None, 'weather_real_time', type_='foreignkey')
    # ### end Alembic commands ###
