"""Create monitor user table

Revision ID: 877cca8c2731
Revises: f4fdcee41afe
Create Date: 2022-11-26 22:01:49.677769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877cca8c2731'
down_revision = 'f4fdcee41afe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitor_user')
    # ### end Alembic commands ###
