"""Setup relationship user - station

Revision ID: a08dc5f45b75
Revises: 877cca8c2731
Create Date: 2022-11-26 22:18:52.132103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08dc5f45b75'
down_revision = '877cca8c2731'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_stations', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'weather_stations', 'monitor_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weather_stations', type_='foreignkey')
    op.drop_column('weather_stations', 'user_id')
    # ### end Alembic commands ###
