"""empty message

Revision ID: d0c168df9425
Revises: 0ac3ebf13836
Create Date: 2022-11-23 22:31:28.249803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c168df9425'
down_revision = '0ac3ebf13836'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_stations', sa.Column('api_key', sa.Text(), nullable=False))
    op.create_unique_constraint('location', 'weather_stations', ['longitude', 'latitude'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('location', 'weather_stations', type_='unique')
    op.drop_column('weather_stations', 'api_key')
    # ### end Alembic commands ###
