"""Cascade parent -> child: station -> conditions

Revision ID: f4fdcee41afe
Revises: 84965ab12140
Create Date: 2022-11-25 20:23:43.493010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fdcee41afe'
down_revision = '84965ab12140'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
